### ISSUE TITLE
some question in docs

### ISSUE THREAD

**Issue by a972667237** [kz26/PyExcelerate#54] opened 2016-08-25 02:31 UTC
Accroding the first code in Styling cells, it lack 'from pyexcelerate import Format' causing the python error.
And if we use Fill, the style setting by Font will become invaild.
My python version is 3.5.1.
My Excel version is 2013.

**Comment by kevmo314** [comment] 2016-08-25 02:48
Thanks, I've updated the documentation. Can you provide code for the behavior you're seeing? I'm guessing that's expected behavior, as set_cell_style sets the current cell to the provided style object. You'd need to create a style with both fill and font set to apply them both.

**Comment by a972667237** [comment] 2016-08-25 04:09
`
from pyexcelerate import Workbook, Color, Style, Font, Fill, Format
wb = Workbook()
ws = wb.new_sheet("test")
ws.set_cell_value(1, 1, 1)
ws.set_cell_style(1, 1, Style(font=Font(bold=True)))
ws.set_cell_style(1, 1, Style(font=Font(italic=True)))
ws.set_cell_style(1, 1, Style(font=Font(underline=True)))
ws.set_cell_style(1, 1, Style(font=Font(strikethrough=True)))
ws.set_cell_style(1, 1, Style(fill=Fill(background=Color(255,0,0,0))))
wb.save("output.xlsx")

`

I try it again , but the result is same.
I also switched the order of Fill and Font, as follow.
`
from pyexcelerate import Workbook, Color, Style, Font, Fill, Format
wb = Workbook()
ws = wb.new_sheet("test")
ws.set_cell_value(1, 1, 1)
ws.set_cell_style(1, 1, Style(fill=Fill(background=Color(255,0,0,0))))
ws.set_cell_style(1, 1, Style(font=Font(bold=True)))
ws.set_cell_style(1, 1, Style(font=Font(italic=True)))
ws.set_cell_style(1, 1, Style(font=Font(underline=True)))
ws.set_cell_style(1, 1, Style(font=Font(strikethrough=True)))
wb.save("output.xlsx")

`

Unfortunately, the font become normal but the fill color disappear.

And finally I create a style object
`

Style(font=Font(bold=True, italic=True, underline=True, strikethrough=True),fill=Fill(background=Color(255,0,0,0)))

`
This code make it work normally.

**Comment by kevmo314** [comment] 2016-08-25 04:17
Yes, this is expected behavior, because you are overriding the style in subsequent calls with a new style object, which contains only the default values. Styles aren't merged in, though [binary operations](https://github.com/kz26/PyExcelerate/blob/dev/pyexcelerate/Style.py#L88) are supported, so you could use this undocumented feature that should work:

```
from pyexcelerate import Workbook, Color, Style, Font, Fill, Format
wb = Workbook()
ws = wb.new_sheet("test")
ws.set_cell_value(1, 1, 1)
ws.set_cell_style(1, 1, Style(fill=Fill(background=Color(255,0,0,0))) | Style(font=Font(strikethrough=True)))
wb.save("output.xlsx")
```

**Closed by kevmo314** 2016-08-25 04:17 UTC
