### ISSUE TITLE
Can' save excel 

### ISSUE THREAD

**Issue by anubhav1** [kz26/PyExcelerate#87] opened 2020-02-26 14:34 UTC
Python : 3.7
OS : Windows 10 64 bit

Below is my code: 
```
 values = [data_df.columns] + list(data_df.values)
 wb = Workbook()
  wb.new_sheet('Sheet1', data=values)
  wb.save(module) ##throws error
```

The last line of the code throws error :
```
Exception has occurred: UnboundLocalError
local variable 'z' referenced before assignment
```

P.S : my dataframe has german characters.

**Comment by kevmo314** [comment] 2020-02-26 15:07
Thanks for the report, do you have a full stack trace or an example that reproduces the issue?

**Comment by kevmo314** [comment] 2020-02-26 15:08
Actually, I'll need the example, it's likely that this is due to pyexcelerate not knowing what data type to classify your data as.

**Comment by anubhav1** [comment] 2020-02-27 07:52
Here is an example reproducing the same error : 

```
from StyleFrame import StyleFrame, Styler
import pandas as pd
from pyexcelerate import Workbook

data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # data is a 2D array
df = pd.DataFrame(data, columns = ['Name', 'Age', 'nu']) 

bgStyle = Styler(bg_color='yellow')
sf = StyleFrame(df)
sf.apply_style_by_indexes([1,2], styler_obj=bgStyle, overwrite_default_style=False)

values = [sf.data_df.columns] + list(sf.data_df.values)
wb = Workbook()
wb.new_sheet('Sheet1', data=values)
wb.save('output.xlsx')
```

**Comment by vaebhav** [comment] 2020-03-08 05:02
Anubhav can you provide the stacktrace of the entire error, I myself have also faced such error , and probably it won't be related to pyexcelerate.

Providing the stacktrace will make it more clear to point you towards the resolution

**Comment by kevmo314** [comment] 2020-03-11 23:01
I've added a change which should allow this to no longer throw an error, however I noticed that you're also using StyleFrame. StyleFrame doesn't advertise compatibility with us and in the test only the values were transferred. You can probably reach out to the StyleFrame developer if they'd like to support PyExcelerate, we'd be happy to work with them.

However, I'd like to avoid adding direct support without their knowledge as they offer a bunch of features that we don't support and vice versa, and would like to avoid a situation where we don't work that well together.

Otherwise, the code you've provided should no longer throw an error so I'll close out this issue.

**Closed by kevmo314** 2020-03-11 23:01 UTC

**Comment by anubhav1** [comment] 2020-03-12 08:20
are new changes available on pypi?

**Comment by DeepSpace2** [comment] 2020-03-12 16:08
@kevmo314 Hi, I'd love to collaborate. I assume/hope that PyExcelerate provides an API similar to openpyxl's API (?)

If that is the case I believe that "all" I have to do is to provide a path in which StyleFrame's `to_excel` method will use PyExcelerate styling mechanism rather than openpyxl's.

However, from what I read PyExcelerate "bread and butter" is performance. Will we benefit even if we need to iterate the worksheet cell by cell?

**Comment by kevmo314** [comment] 2020-03-12 16:42
@anubhav1 Not yet, I'll push a release soon.

@DeepSpace2 Yes, the API is documented [here](https://github.com/kz26/PyExcelerate#styling-cells). I think in principle you can generate the various style objects, then loop over the worksheet with `set_cell_style`. This shouldn't be too expensive with respect to performance so a lot of the speed can be retained even with iterating over the worksheet. I think it would be worthwhile to try minimizing the number of PyExcelerate style objects that are created, ie don't create new PyExcelerate styles for every cell. The output library tries merging equivalent styles which can be expensive if they're not identical by reference. If StyleFrame already has style objects, then mapping them to PyExcelerate's objects then writing cell-by-cell should be pretty performant.
