### ISSUE TITLE
string data is stripped

### ISSUE THREAD

**Issue by netzkr** [kz26/PyExcelerate#89] opened 2020-04-03 08:19 UTC
wb=Workbook()
ws=wb.new_sheet('sh')
ws.set_cell_value(1,1,'      I have spaces    ')
wb.save('temp.xlsx')

when I open the temp.xlsx
there is no spaces before 'I have spaces   '

thank you for your very good and fast works anyway~!!

**Comment by kevmo314** [comment] 2020-04-03 13:43
Duplicate of #86, this should be fixed in the next release. It's in the dev branch if you want it right now :)

**Closed by kevmo314** 2020-04-03 13:43 UTC
